repos:
-   repo: https://github.com/willthames/ansible-lint.git
    sha: v3.4.16
    hooks:
    -   id: ansible-lint
        files: \.(yaml|yml)$
        name: Ansible-lint
        description: This hook runs ansible-lint.
        language: python
