repos:
-   repo: https://github.com/willthames/ansible-lint.git
    rev: v4.1.0
    hooks:
    -   id: ansible-lint
        files: \.(yaml|yml)$
        exclude: (wercker.yml|.*/marathon-app/meta/main.yml)
        name: Ansible-lint
        description: This hook runs ansible-lint.
        language: python
