---

- name: Create group for Airflow
  group:
    name: '{{ airflow_group }}'
    state: present

- name: Create user for Airflow
  user:
    name: '{{ airflow_user }}'
    group: '{{ airflow_group }}'
    home: '{{ airflow_home }}'
  when: airflow_user != 'vagrant'

- name: Create airflow home
  file:
    path: '{{ airflow_home}}'
    state: directory
    owner: '{{ airflow_user }}'

- name: Install required Debian packages
  apt:
    pkg: '{{ item }}'
    state: present
    update_cache: yes
    cache_valid_time: 600
  with_items: "{{ airflow_deb_packages }}"

- name: Install required Python packages
  pip:
    name: '{{ item }}'
    executable: '{{ airflow_pip }}'
    state: present
  with_items: "{{ airflow_pip_packages }}"

- name: Install required Debian packages for plugins
  apt:
    pkg: '{{ item }}'
    state: present
    update_cache: yes
    cache_valid_time: 600
  with_flattened: "{{ airflow_plugins|map(attribute='required_debs')|list }}"

- name: Install required Python packages for plugins
  pip:
    name: '{{ item }}'
    executable: '{{ airflow_pip }}'
    state: present
  with_flattened: "{{ airflow_plugins|map(attribute='required_pips')|list }}"

- name: Install airflow (first time installation takes a long time)
  pip:
    name: 'airflow=={{ airflow_version }}'
    executable: '{{ airflow_pip }}'
    state: present

- name: Fix Python path in Airflow scripts
  lineinfile:
    dest: /usr/local/bin/airflow
    regexp: '^#!.*'
    line: '#!{{ airflow_python }}'

- name: Install airflow plugins
  pip:
    name: 'airflow[{{ item.name }}]=={{ airflow_version }}'
    executable: '{{ airflow_pip }}'
    state: present
  with_items: "{{ airflow_plugins }}"

- name: Generate Fernet key
  ferney_key:
    config_file: '{{ airflow_config}}'

- name: Setup configuration for airflow
  template:
    src: airflow.cfg.j2
    dest: '{{ airflow_config}}'
    owner: '{{ airflow_user }}'
    mode: 0640

- name: Remove uncompatible DAG example (example_twitter_dag.py)
  file:
    path: /usr/local/lib/python2.7/dist-packages/airflow/example_dags/example_twitter_dag.py
    state: absent

- name: Launch Airflow Initdb
  command: "/usr/local/bin/airflow initdb"
  register: airflow_initdb_result
  environment:
    AIRFLOW_HOME: "{{ airflow_home }}"
    PYTHONPATH: "{{ airflow_python_libraries_path }}"
  become: true
  become_user: '{{ airflow_user }}'
  changed_when: "airflow_initdb_result.rc != 0 or airflow_initdb_result.stdout.find('Running upgrade') >= 0"
  when: airflow_install_master

- name: Launch Airflow Upgradedb
  command: "/usr/local/bin/airflow upgradedb"
  register: airflow_upgradedb_result
  environment:
    AIRFLOW_HOME: "{{ airflow_home }}"
    PYTHONPATH: "{{ airflow_python_libraries_path }}"
  become: true
  become_user: '{{ airflow_user }}'
  changed_when: "airflow_upgradedb_result.rc != 0 or airflow_upgradedb_result.stdout.find('Running upgrade') >= 0"
  when: airflow_install_master

- name: Generate the database configuration script
  template:
    src: airflow_db_config.py.j2
    dest: '{{ airflow_home }}/airflow_db_config.py'
    owner: '{{ airflow_user }}'
    group: '{{ airflow_group }}'
    mode: 0640

- name: Launch Airflow Upgradedb
  command: "{{ airflow_home }}/airflow_db_config.py"
  environment:
    AIRFLOW_HOME: "{{ airflow_home }}"
    PYTHONPATH: "{{ airflow_python_libraries_path }}"
  become: true
  become_user: "{{ airflow_user }}"

- name: Install Airflow scripts
  git:
    repo: '{{ item.url }}'
    version: "{{ item.version | default('latest') }}"
    verify_commit: "{{ item.verify_commit | default(False) }}"
    key_file: "{{ item.key_file | default(None) }}"
    dest: '{{ item.dest }}'
    depth: 1
    force: yes
    update: yes
  with_items: "{{ airflow_scripts }}"
  tags:
    - airflow_scripts

- include: marathon.yml
  when: airflow_startup == 'marathon'
