---

version: 2
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: hbpmip/docker-compose-for-ci:18.09-1
    environment:
       - CIRCLECI: true
    steps:
      - setup_remote_docker:
          version: 17.06.0-ce
      - checkout
      - run:
          name: "Install requirements"
          command: |
            docker --version
            pre-commit install
            mkdir -p .molecule/roles
            git clone https://github.com/ludovicc/ansible-marathon_app.git ../marathon-app
            apk --update --no-cache add libffi-dev openssl-dev linux-headers ansible
            pip install --upgrade pip
            pip install --upgrade ansible
            pip install -r tests/requirements.txt
      - run:
          name: "Validate code quality"
          command: |
            pre-commit run --all-files
