---
ansible:
  verbose: vv
  playbook: tests/playbook.yml
  diff: True
  config_file: ../ansible.cfg

dependencies:
  name: galaxy
  requirements_file: tests/requirements.yml

platforms:
- name: ubuntu
  image: ubuntu:16.04
  environment:
    container: docker
  groups:
    - airflow